---
title: "Title Goes Here"
author:
  - Author One
  - Author Two
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::html_document2:
    fig_caption: yes
    reference_docx: "../templates/jas/template.docx" # Insert path for the DOCX file
bibliography: references.bib
csl: "../templates/jas/journal-of-archaeological-science.csl" # Insert path for the bib-style
abstract: |
  Text of abstract
keywords: |
  keyword 1; keyword 2; keyword 3
highlights: |
  These are the highlights. 
---


<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

```{r, setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "figures"
)

devtools::load_all(".", quiet = T)
```

# Introduction

Here is a citation [@Marwick2017]

# Background

```{r demo, eval = FALSE}
1 + 1
```

# Methods

# Results

```{r get-data, eval = FALSE}
# Note the path that we need to use to access our data files when rendering this document
# my_data <- readr::read_csv("../data/raw_data/my_csv_file.csv")
```

# Discussion

# Conclusion

# Acknowledgements

# References 
<div id="refs"></div>

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? You may need to change the path value
# if your Rmd is not in analysis/paper/
git2r::repository("../..")
```


