version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Get info
          command: docker info
      - run:
          name: Build the custom container
          command: docker build -t $DOCKER_USER/rrtools  .
          no_output_timeout: 4h
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login --username=$DOCKER_USER --password=$DOCKER_PASS
            docker push $DOCKER_USER/rrtools
