---
title: "My title"
author:
- author 1
- other author
date: '`r Sys.Date()`'
output: word_document
abstract: "My abstract \n"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Heading 1

## Heading 2

### Heading 3

#### Heading 4

##### Heading 5 - this is for the page break with MS Word

In the MS Word document, the following modifications must be made in the 'Modify Style' menu:

+ Set the font color to ‘white’ (rather than ‘Automatic’).
+ Select the smallest font size (8 rather than 11).
+ Select ‘Page break before’ in the ‘Line and Page Breaks’ tab.
+ Set the line spacing to ‘Exactly’ and ‘1 pt’ in the ‘Indents and Spacing’ tab.

After these tweaks, the ‘Heading 5’ style will no longer format a heading of level 5. Instead it will insert a very small and white (and, thus, invisible) line followed by a page break.

Now knit this doc, and edit the styles in the resulting docx file. Then rename as 'template' and use this in the yml:

```
output:
  word_document:
    reference_docx: templates/template.docx
```

Don't forget line numbers for JAS! Headings are bold, underline, nothing. And Arial Narrow 10pt for tables.

See here for more information: http://rmarkdown.rstudio.com/articles_docx.html
