# get the base image, the rocker/verse has R, RStudio and pandoc
FROM rocker/{{{rocker}}}:{{{r_version}}}

# required
MAINTAINER Your Name <your_email@somewhere.com>

COPY . /{{{repo}}}

# go into the repo directory
RUN . /etc/environment \
  # Install linux depedendencies here
  # e.g. need this for ggforce::geom_sina
    && sudo apt-get update \
    && sudo apt-get install libudunits2-dev -y \
  # remove symbolic links so Docker doesn't complain that target files don't exist
    && sudo rm -R /{{{repo}}}/packrat/lib/* \
    && sudo rm -R /{{{repo}}}/packrat/lib-ext/* \
    && sudo rm -R /{{{repo}}}/packrat/lib-R/* \
  # build this compendium package
    && R -e "devtools::install('/{{{repo}}}', dep=TRUE)" \
  # set all packages to correct versions
    && R -e "install.packages('packrat'); packrat::restore(project = '/{{{repo}}}', overwrite.dirty = TRUE, prompt = FALSE)" \
  # put private package library created by packrat first among the library trees within which packages are looked for
  # render the manuscript into a .html, you'll need to edit this if you've
  # customised the location and name of your main Rmd file
    && R -e ".libPaths(c(file.path(normalizePath('{{{repo}}}', winslash = '/', mustWork = TRUE), 'packrat/lib', file.path(R.version$platform, getRversion())), .libPaths())); rmarkdown::render('/{{{repo}}}/{{{rmd_path}}}')"
